### ISSUE TITLE
Not able to install plugin

### ISSUE THREAD

**Issue by cheapsteak** [oddmouse/cordova-plugin-locktask#10]
Get the following message after running  
`cordova plugin add https://github.com/oddmouse/cordova-plugin-locktask.git`
```bash
Error: Failed to fetch plugin https://github.com/oddmouse/cordova-plugin-locktask.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! cb() never called!
```

**Comment by QuentinRoy** [comment]
Try with `cordova plugin add cordova-plugin-locktask` instead.

**Comment by cheapsteak** [comment]
That seems to belong to a different repo?

https://github.com/mschez/cordova-plugin-locktask

**Comment by QuentinRoy** [comment]
Oh. I did not noticed. Indeed.

**Comment by QuentinRoy** [comment]
Are you using cordova 7? Cordova 7 requires a `package.json` file (because it uses `npm` under the hood). This plugin does not provide a `package.json` file so it won't get installed.

**Comment by cheapsteak** [comment]
ah, that makes sense, thanks!

**Comment by oddmouse** [comment]
I just added a `package.json` for you. Feel free to submit a PR if there is anything else needed to bring it up to date.
