### ISSUE TITLE
Set up the device owner from Cordova

### ISSUE THREAD

**Issue by gaa-cifasis** [oddmouse/cordova-plugin-locktask#7]
Hi,

I'm trying to use this plugin in a Cordova project. I'm not sure how set up it as the device owner (as explained in the [device admin section](https://github.com/oddmouse/cordova-plugin-locktask#device-admin). Can you give me some hint, maybe with a small example?

Thanks!

**Comment by oddmouse** [comment]
The steps outlined should get you there. Are you having an issue with a particular step?

**Comment by gavrochelegnou** [comment]
Hello, 
I do have an issue on step 3 : 
"Add a device admin sub class of DeviceAdminReceiver"
I do not understand where exactly to put this piece of code ?
Thanks a lot !

**Comment by oddmouse** [comment]
I just updated the readme to clarify that part. It should be in your project‘s source package.

`platforms/android/src/com/example/package/ExampleAppAdmin.java`

**Comment by gaa-cifasis** [comment]
Thanks!
